### ISSUE TITLE
[Bug] Json group invite stores the date incorrectly

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#26]
The JSON given as a response from the server when the user tries to create a group invite incorrectly stores the date, and as such cannot be retrieved correctly by the client.

I. E.:
[Current] { ... dateCreated: 123024903432 ... }
[Expected] { ... dateCreated: "123024903432" ... }

**Comment by StormFireFox1** [comment]
Alright, so I'm not sure if this is something I'm supposed to change.
> I. E.:
> [Current] { ... dateCreated: 123024903432 ... }
> [Expected] { ... dateCreated: "123024903432" ... }

Well, 'dateCreated' is supposed to be an integer, since it's the seconds from
the Unix epoch. I mean, I could theoretically change it to a simple plain-text
interpretation of date (read ISO 8601), but it seems easier to just use the
integer. I will change if requested, but I'm just offering advice.

**Comment by StormFireFox1** [comment]
Alright, so I'm not sure if this is something I'm supposed to change.

> I. E.:
> [Current] { ... dateCreated: 123024903432 ... }
> [Expected] { ... dateCreated: "123024903432" ... }

Well, 'dateCreated' is supposed to be an integer, since it's the seconds from
the Unix epoch. I mean, I could theoretically change it to a simple plain-text
interpretation of date (read ISO 8601), but it seems easier to just use the
integer. I will change if requested, but I'm just offering advice.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io
