### ISSUE TITLE
[Bug] No suitable response for wrong request body

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#28]
If a wrong request body is sent to the server (missing/badly named fields), no suitable response is given back. Instead, the server tries to proceed with the request, which might lead to undesired results.

**Comment by StormFireFox1** [comment]
On 19/06/06 04:05AM, Alexandru Gherghescu wrote:
> If a wrong request body is sent to the server (missing/badly named fields), no suitable response is given back. Instead, the server tries to proceed with the request, which might lead to undesired results.

If I recall, I think that this "catch" clause from https://github.com/CNITV/SQLiggyBank/blob/8ad8441e29eeae26175b152083eeb6765d461117/server/src/main/java/ro/lbi/sqliggybank/server/Resources/BanksResource.java#L207-L211
checks for badly named fields or otherwise unmappable request bodies, and a
similar clause can be found in all "POST" handling endpoints. If you can find
a situation where there isn't such clause, do tell me and I'll fix it.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io

**Comment by alexghergh** [comment]
For example, the endpoint **{{host}}/api/users/new**. Whenever you try to use the endpoint with a request body that contains no username, there is a 500 server error on it.

(This is possibly present in other requests as well.)

**Comment by alexghergh** [comment]
Can confirm it is present in other requests as well; for example **{{host}}/api/users/login** with a request body that doesn't include a password (only a username). Is this something that needs to be fixed or a 500 server error is a suitable response (seems unlikely to me)?
