### ISSUE TITLE
[Bug] Cannot modify goal information

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#35]
Similar to issue #32. Wrong UPDATE statement.

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/191e40e339a71947a0a6035aedf194a8c738cf94).

The problem wasn't with a faulty UPDATE statement. Rather, the server did not check for potential null fields in the sent JSON. This has been fixed for Goal, since most of the other objects already have certain checks in place for non-null constraints.

This problem propagated to BanksResource as well in issue #32, only with the only non-null constraint there, the group in which the bank is in.
