### ISSUE TITLE
[Bug] There can be multiple goals with the same name

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#40]
Currently, the database allows for multiple goals with the same name, within the same bank. There should be just one goal with a name in a bank (Of course, there can be multiple goals with the same name in different banks.)

**Comment by StormFireFox1** [comment]
Thanks to this commit:
https://github.com/CNITV/SQLiggyBank/commit/c28e69e3dbb1ebf5219d3a066954c59355153879

The problem is fixed. Since the check works within the context of the piggy bank
the user is intending to add the goal to, it effectively checks the problem you
described.

Yay for redundant issues!

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io
