### ISSUE TITLE
[Bug] UUID is seen when a group is created

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#45]
Although the UUID of a group is no longer public when a user tries to get group information, it is still available when the user created a group.

Endpoint: {{host}}/api/groups/new

**Comment by StormFireFox1** [comment]
Well, ain't this sad.

Technically, I can't change that because of the way invites work right now. The
only way to make sure invites work is that they contain the group UUID in them,
and that's really the only way. I guess I could redact the UUID upon finishing
with it which is what I'll do, I guess.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io
